liferay/liferay-frontend-guidelines

guidelines/general/branch_structure.md

Closes: https://github.com/liferay/liferay-frontend-guidelines/issues/9

docs: Add branch structure guidelines (#9)

---

guidelines/general/testing.md

Just a tiny recommendation to seed the document. There are lots more things that could be said about testing, and it can get pretty subjective, so I thought I'd start with something relatively uncontroversial, but which has come up in code review quite a bit.

docs: add initial recommendations for testing

---

guidelines/dxp/formatting.md

See: https://github.com/liferay/liferay-npm-tools/issues/117

docs: update dxp/formatting.md to match liferay-npm-scripts v3.0.0

---

guidelines/general/formatting.md

Small typo in general formatting guidelines table

Small doc typo

---

patterns/dxp/requests.md

docs: fix typo in patterns/dxp/requests.md

---

general/typescript.md

Based on discussion in https://github.com/liferay/clay/pull/2169 this commit adds a very brief note that doesn't aim to exhaustively define best practices; it just seeks to answer the question of can/should you use TypeScript in Liferay projects.

docs: add general/typescript.md

---

general/testing.md

As evidenced by this mega thread:
https://github.com/jbalsas/liferay-portal/pull/1819#discussion_r303149958
This is a very complex topic with lots of tradeoffs and historical context to weigh up. As such, this PR seeks to make some modest progress by starting with some minimal guidelines. We begin with the bits that are clear and uncontroversial. As we move deeper into the topic, things become more complicated and harder to make recommendations on (and we probably get diminishing returns anyway).

docs: add recommendations for testing UI components

---

dxp/drag_and_drop.md

This is just intended to be a summary of the discussion in #39, and not the "final word" on drag and drop in liferay-portal.
Closes: https://github.com/liferay/liferay-frontend-guidelines/issues/39
Related: https://issues.liferay.com/browse/LPS-99879

docs: add dxp/drag_and_drop.md

---

.github/semantic.yml

Seeing as I just noticed that it's actually been configured for this repo.

feat: configure Semantic Pull Request bot

---

general/testing/README.md

Inspired by [discussion in this PR](https://github.com/jbalsas/liferay-portal-ee/pull/67#discussion_r321211721), and elsewhere.

docs: clarify what is meant by "one assertion per block"

---

general/imports.md

Closes: https://github.com/liferay/liferay-frontend-guidelines/issues/60

docs: document importing conventions

---

general/branch_structure.md

We're using this in two places now, so let's document it.

docs: mention liferay-js-publish

---

general/comments.md

Combined everybody's input from the original issue.
No enforcement (linting) for this stuff yet, and we may not need it unless we find that we have consistency problems.
Closes: https://github.com/liferay/liferay-frontend-guidelines/issues/96

docs: add general/comments.md (#96)

---

css/when_and_how_to_create_a_new_css_component.md

style: fix formatting

---

general/react.md

Seeing as this comes up in code review a lot, seeding the React-recommendations with this guideline. Obviously, will probably add more things over time, but this is a start.

docs: add notes on React `key` attribute

---

dxp/dev_dependencies.md

docs: add considerations before adding new dependencies

---

dxp/how_to_use_css_custom_properties.md

- Minor grammar fixes.
- No "smart" apostrophes (we weren't using them consistently in this file anyway).
- Run Prettier.

docs(ccp): apply some copy-editing fixes

---

.github/workflows/nodejs.yml

Just did this over in liferay-ckeditor and it was pretty straightforward, so let's try it here too.
https://github.com/liferay/liferay-ckeditor/pull/52

feat: set-up CI in this repo

---

.github/workflows/nodejs.yml

Two things:
- Don't install `yarn` because it's already there.
- Add `--frozen-lockfile` to catch another class of mistakes.

refactor: improve actions set-up

---

css/clay_css_2_recipes/01_getting_started.md
css/clay_css_2_recipes/02_buttons.md
dxp/debounce_and_throttle.md
general/testing/README.md
support/checkLinks.js

issue #80
Instead of trying to figure out all the questions devs may have about Clay CSS, I thought documenting the framework through a cookbook format might be better answering questions that may arise. I wasn't sure where to put it, let me know if there's a better place and anything that needs more clarification.

docs: Adds Clay CSS 2 Recipes Getting Started

---

css/clay_css_2_recipes/03_text_input.md

docs: Adds Clay CSS 2 Recipes Text Input

---

css/clay_css_2_recipes/04_checkbox_radio.md

docs: Adds Clay CSS 2 Checkbox Radio recipe

---

css/clay_css_2_recipes/05_toggle_switch.md

docs: Adds Clay 2 Toggle Switch Recipe

---

support/checkLinks.js

Since https://github.com/liferay/liferay-frontend-guidelines/pull/161 Cloudflare has been 503-ing these links.
They used to 403 them, and we got around that in https://github.com/liferay/liferay-frontend-guidelines/pull/134, but it looks like the party is over now, and I don't think it is worth trying to keep up with them on this one. [Another example of a PR](https://github.com/liferay/liferay-frontend-guidelines/pull/163) with a
spurious failure due to these links.

fix: give up on trying to check codepen.io links

---

dxp/exporting.md

docs(dxp): add documentation about exporting

---

dxp/bundler_imports.md
general/bundler_imports.md

docs: document npm bundler imports

---

dxp/frontend_taglib_clay.md

I wasn't sure how in depth we want to go with these. I initially had more content but it felt over-wordy. Let me know if there are any other caveats or nuances to note with this.

docs: document frontend-taglib-clay and it's relation with @clayui components

---

.eslintrc.js
css/clay_css_2_recipes/06_clay_range.md
package.json
support/checkLinks.js
yarn.lock

Closes: https://github.com/liferay/liferay-frontend-guidelines/pull/172

chore: update dependencies

---

general/session.md

First time making a PR here, so let me know if I did something wrong! IDK how to check if the markdown is good, and hopefully the commit & PR names are good.

docs: Document Session API

---

dxp/resource_injection.md

docs: document resource injection support in DXP

---

general/glossary.md
support/checkLinks.js

This is a proposal for a glossary. I have added the terms and products that came to my mind but I'm sure we have much more. 
The idea is to update this glossary any time we discuss about terminology in a PR and decide something so that we can all look up these terms here when we are writing documentation.

docs: glossary

---

dxp/layout_rendering.md

Set to Draft state because I need to add the last section and link source code.

docs: document layout rendering in DXP

---

dxp/aui_script.md
dxp/demystifying_aui_script_and_liferay-frontend_component_tags.md
dxp/liferay_frontend_component.md

docs: Adds Demystifying `aui:script` and `liferay-frontend:component` tags docs

---

dxp/clay-css-3-intro.md

Requested by @jbalsas, not sure what directory to place this in. I feel like this information is/will be duplicated in a lot of other documents (#213).
/cc @marcoscv-work @eduardoallegrini

docs: Clay CSS 3.x introduction

---

dxp/code_review.md

I have previously shared this info in Slack, but I want to increase the likelihood that somebody will find it in the event that I get hit by a bus.

docs: describe team repo sync script
