README.md
Seeing as I wrote this over in [this comment](https://github.com/liferay/liferay-frontend-guidelines/issues/13#issuecomment-499415127), I figured I may as well add it to the README.
=> docs: add info about development process to README.md

guidelines/general/file_names.md
It's supposed to be "test" not "tests"; elsewhere in this same doc we get it right, but it's wrong in this one place.
=> docs: fix typo in file_names.md

guidelines/dxp/dev_dependencies.md
I noticed that the footnote doesn't properly link to the `Related resources` section.
=> docs: fix footer reference on dev_dependencies.md

general/commit_messages.md
Note that it says, "In this repo, we use the Semantic Pull Request bot..."
Once we've set it up in other repos we should remove the "In this repo" bit.
=> docs: add links related to the Semantic Pull Request bot

dxp/urls.md
Via `yarn format`.
I actually ran `yarn format` earlier today and used that to produce [this pull](https://github.com/liferay/liferay-frontend-guidelines/pull/69) but I must have been on an old merge base at the time, because running it again on "master" now I produced this diff.
Pretty amazing that Prettier formats the JS inside the fenced code blocks in a Markdown file.
=> style: fix formatting in dxp/urls.md

dxp/environment.md
As of https://github.com/brianchandotcom/liferay-portal/pull/77109 `nodejs.node.env` defaults to empty (which is basically equivalent to "production") instead of an explicit "production".
The motivation for the change is described [here](https://github.com/brianchandotcom/liferay-portal/pull/77081#issuecomment-522001727).
=> docs: update environment description to reflect recent changes

.github/ISSUE_TEMPLATE/Proposal.md, .github/ISSUE_TEMPLATE/Question.md, .github/ISSUE_TEMPLATE/devDependency.md, README.md, dxp/dev_dependencies.md, dxp/drag_and_drop.md
This can probably be improved but adding some "seed" versions to get the ball rolling.
~~Still TODO (future): figure out how to auto-label issues based on the template used.~~
Replaces: https://github.com/liferay/liferay-frontend-guidelines/pull/23
=> feat: add issue templates

.eslintrc.js, dxp/dev_dependencies.md, general/testing/supported_libraries.md, package.json, support/checkLinks.js, yarn.lock
Seeing as some of these have crept in of late.
Running it on the current version of the exposes these two problems:
dxp/dev_dependencies.md: Missing reference: liferay dxp build process
general/testing/supported_libraries.md: No file/directory found for local target: general/dxp/dev_dependencies.md
I fix those in the second commit in this PR.
=> feat: add script to check for broken links

dxp/environment.md
I guess this is stable enough to document it; the setting is already the recommended default in [the canonical "portal-developer.properties" file](https://github.com/liferay/liferay-portal/blob/a0efb8c930d3246f80cc349dba4f0c85be8a4768/portal-impl/src/portal-developer.properties#L22).
Initial feedback on the performance and reliability of the feature can be found in [this #guild-frontend-es thread](https://app.slack.com/client/T03BTCQAJ/C25TXMD63/thread/C25TXMD63-1569956211.028100) (in Spanish 😂).
Closes: https://github.com/liferay/liferay-frontend-guidelines/issues/97
=> docs: document "deployFast" (#97)

dxp/environment.md
It's not clear that having the cache is always beneficial, although it sometimes is, so trying to reflect that in the documentation.
=> docs: document liferay/liferay-binaries-cache-2020

dxp/dev_dependencies.md, general/package_structure.md
Trying to gather together some common patterns that we use in multiple places, and have something that we can reference instead of scattered comments across GitHub like the ones I made [here](https://github.com/liferay/clay/pull/2605) and elsewhere.
=> docs: add general/package_structure.md

general/javascript.md
Principally to document what Babel features we make use of and why we have a relatively conservative policy about enabling support for new proposals.
Wrote this because I was commenting about [a stage 3 proposal over here](https://github.com/liferay/clay/pull/2609/files/98b19da51617b1b1529bee75f1038032c74f0c11#r333350296) and that made me want to see if we had documented anywhere what our "official" stance on stage 3 and stage 4 stuff is.
=> docs: add "javascript.md"

general/file_names.md
Closes: https://github.com/liferay/liferay-frontend-guidelines/issues/24
=> docs: fix misleading guidance about the ".tsx" extension (#24)

general/typescript.md
I found this repo recently and it was pretty helpful to see other examples of TS + react. I thought it would be helpful for us to provide a link for additional resoruces.
Also, the maintainers are pretty active, so thats a plus.
=> docs: Add reference to react-typescript-cheatsheet resource

package.json
Analogous change to this one on the alloy-editor repo:
https://github.com/liferay/alloy-editor/pull/1374
Just in case anybody is ever foolhardy enough to try doing development on this repo on Windows.
=> fix: make globs work on Windows

support/checkLinks.js
As explained in the related issue, Cloudflare rejects our link checks with a 403 and an HTML page that asks us to fill out a CAPTCHA. I checked to see if some lighter-weight check like an OPTIONS request avoided the issue, but it doesn't.
So, grabbed some headers from the Firefox network pane and this seems to be a reasonably minimal not-robot-like set that lets the requests succeed.
Closes: https://github.com/liferay/liferay-frontend-guidelines/issues/133
=> fix: stop checkLinks.js from freaking out about codepen.io links

.github/workflows/ci.yml, README.md
Renames "Node.js CI" to "ci" and adds a badge showing status to the README.
=>  docs: add build status badge to README

support/checkLinks.js
As discussed [here](https://github.com/liferay/liferay-frontend-guidelines/pull/140#discussion_r402427606), we have some more challenging heading and link types to handle in that doc; eg.
- Headings with colons.
- Headings with backticks.
- Headings with links.
- Combinations of the above.
- Links whose case doesn't match the case of the GitHub-generated anchor.
- Links that use a novel angle-bracket syntax (eg. `[text](<http://example.com>)`).
Examples:
Headings:
Links:
of the new [JavaScript APIs](#JavaScript)
(actual anchor is #javascript)
[text](<http://example.com>)
=> fix: teach checkLinks.js to handle more heading and link types

dxp/architecture/rich_text_editors.md
Didn't notice while reviewing the Markdown source in [#140](https://github.com/liferay/liferay-frontend-guidelines/pull/140) but caught it while looking at [the final result](https://github.com/liferay/liferay-frontend-guidelines/blob/d1233ead83a8b8de776175fbc11da8e99f53267a/dxp/architecture/rich_text_editors.md).
=> docs: fix broken Markdown link

dxp/debounce_and_throttle.md, general/testing/README.md, package.json, support/checkLinks.js, yarn.lock
Will solve one of the issues that `yarn audit` complains about (#126).
Note that because this pulls in a new version of Prettier, there are some formatting changes included, and we have to add blank line before `return` statements to avoid these errors which come with the latest version of eslint-config-liferay:
```
checkLinks.js
114:4  error  Expected blank line before this statement  padding-line-between-statements
171:5  error  Expected blank line before this statement  padding-line-between-statements
177:4  error  Expected blank line before this statement  padding-line-between-statements
182:4  error  Expected blank line before this statement  padding-line-between-statements
187:4  error  Expected blank line before this statement  padding-line-between-statements
192:4  error  Expected …
```
=> chore: update dependencies

package.json, yarn.lock
Just a routine update based on output of `yarn outdated`, and then regenerated lockfile as per:
https://github.com/eslint/eslint/issues/13050
This gives us a clean `yarn audit`, getting rid of:
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ eslint …
=> chore: update dependencies and regenerate lockfile

dxp/formatting.md, general/formatting.md
As pointed out [here](https://github.com/markocikos/liferay-portal/pull/188#issuecomment-635818859), the info here was stale and did not reflect [the latest editor integration guidelines](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts#editor-integrations).
Rather than copy them here (and risk them getting out of sync), I just linked to them.
Note: CI is going to fail on this because CloudFlare has decided to 503 the link verification requests (again). I'll fix that in a separate pull.
=> docs: add links to Liferay-specific editor integration info

general/file_names.md
Seeing as this came up [in review here](https://github.com/liferay-frontend/liferay-portal/pull/48#discussion_r450509707) I thought we may as well document it. Specifically, the question is how to name a file that exports a bunch of constants.
We have a tension between what our simple rule ("file names should match their contents") would imply, and what we are actually doing in liferay-portal.
So, given that this document is somewhat aspirational in nature (ie. describing what we should do even if it doesn't yet match what we actually do), I've noted that we should be doing (use all caps in the name) and also what we tend to do in liferay-portal up to today... Maybe one day we will be able to change this.
Note that there are still two approaches to defining constants that we could debate, …
=> docs: add some additional notes on file naming (constants)

general/naming.md
This came up in code review again:
https://github.com/liferay/clay/pull/3684#discussion_r484662169
So I figure it is time to finally document this.
For now starting with abbreviations, but we can add more naming-related things in the future. It is one of the two hard problems, after all...
The examples of "bad" abbreviations are all taken from past code reviews.
Not intended to be exhaustive advice, but it's a start.
Closes: https://github.com/liferay/liferay-frontend-guidelines/issues/159
=> docs: add initial naming guidelines

dxp/javascript_minification.md, support/checkLinks.js
Document infrastructure for JavaScript minification in DXP .
See #177.
> This CI build is failing because #200 has not been merged and references files in it.
=> docs: JavaScript minification in DXP

CONTRIBUTING.md, general/linking.md
Because it just came up again here:
https://github.com/liferay/liferay-frontend-guidelines/pull/226#discussion_r499599667
=> docs: add guidance on "evergreen" linking

general/linking.md
- One to make it even clearer.
- The other to correct a grammar mistake.
=> docs: minor editions in `linking.md`

dxp/resource_serving.md
As per [this PR](https://github.com/liferay/liferay-frontend-guidelines/blob/b92822feab6d29b77ee1af9b98be61cc30a8cd4e/dxp/aui_script.md#inline-js-on-the-jsp) explain how `AggregateFilter` also consolidates all `<aui:script>` code into one single block.
=> docs: relate <aui:script> to Aggregate Filter

dxp/taglib_aui_input.md
This is the first round of `aui:input` documentation. There is still a bit more to do, but I figured we can start reviewing what I have so far. Things that still need to be documented (that I know of) are marked with TODO.
=> docs: Adds Demystifying `aui:input` tag
